/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif


#ifndef PAVING_H
#define PAVING_H

#include <stdlib.h>
#include <gtk/gtk.h>
#include "support.h"

#define PAVING_BUTTON1 21
#define PAVING_BUTTON2 22
#define PAVING_BUTTON3 23
#define PAVING_BUTTON4 24
#define PAVING_BUTTON5 25
#define PAVING_BUTTON6 26
#define PAVING_BUTTON7 27
#define PAVING_BUTTON8 28
#define PAVING_BUTTON9 29
#define PAVING_BUTTON10 30
GtkWidget *paving_new_button_block(gint rank, gchar *strFile, gchar *str );
GtkWidget *paving_window(APP_data *user_data );
#endif /* PAVING_H */

