/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif


#ifndef SEARCH_H
#define SEARCH_H

#include <poppler.h>
#include "support.h"
#include "misc.h"

void
find (GtkWidget *view, GtkTextBuffer *buffer, const gchar *text, GtkTextIter *iter, gint direction);
void
find_next (GtkWidget *view, GtkTextBuffer *buffer, const gchar *text);
void
find_previous (GtkWidget *view, GtkTextBuffer *buffer, const gchar *text);
gint search_count_matches(GtkTextBuffer *buffer, const gchar *text);
GList *search_hits_inside_PDF_page(PopplerPage *Page, const gchar *text);
void search_free_PDF_search_datas(APP_data    *data);
gint search_hits_inside_PDF_document(APP_data    *data, const gchar *tmpStr);
void search_draw_selection_current_page(gint page, APP_data    *data, cairo_surface_t *surface);
gint search_goto_prev_PDF_page(gint page, APP_data    *data);
gint search_goto_next_PDF_page(gint page, APP_data    *data);
#endif /* SEARCH_H */
