/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif


#ifndef SETTINGS_H
#define SETTINGS_H

#include <stdlib.h>
#include <gtk/gtk.h>
#include "support.h"
#include "misc.h"

/* functions */

GtkWidget *create_prefs_dialog (GtkWidget *win, APP_data *data_app);

#endif /* SETTINGS_H */
